project:
  type: website
    
website:
  site-url: https://pycta.github.io/
  repo-url: https://github.com/pycta/pycta.github.io/
  favicon: favicon.ico
  title: "Jann Schöngart"
  navbar:
    left:
      - text: "My research"
        href: index.qmd
      - text: "About me"
        href: about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

execute:
  freeze: auto
  
